<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Str;

/**
 * App\Models\Product
 *
 * @property int $id
 * @property string $name
 * @property int $price_in
 * @property int $price_out
 * @property string $description
 * @property string $thumb
 * @property int $id_category
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|Product newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Product newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Product query()
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereIdCategory($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product wherePriceIn($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product wherePriceOut($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereThumb($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property string $slug
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Categories[] $categories
 * @property-read int|null $categories_count
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereSlug($value)
 */
class Product extends Model
{
    use HasFactory;
    protected $table = 'product';
    protected $guarded = [
        'id'
    ];
    public function categories(){
        return $this->hasMany(Categories::class,'id','id_category');
    }
    public  function save(array $options = [])
    {

        $this->slug = Str::slug($this->name, '-');
        return parent::save($options); // TODO: Change the autogenerated stub
    }

}
